name: project_sayogi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9

  # ðŸ”¹ State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # ðŸ”¹ Networking
  dio: ^5.7.0
  http: ^1.2.1

  # ðŸ”¹ OTP Input
  pinput: ^5.0.1

  # ðŸ”¹ Toast Notifications
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mainlogo.png
    - assets/google.png
    - assets/facebook.png
    - assets/bar.png
    - assets/verify.png
    - assets/homeg.jpeg
    - assets/site.png
    - assets/karobar.png
    - assets/maindash.png
    - assets/partiharu.png
    - assets/profilephoto.png
    - assets/incomehome.png
    - assets/expensehome.png
    - assets/amountreceivehome.png
    - assets/amounttogivehome.png
    - assets/notification1.png
    - assets/notetitle.png
